### ISSUE TITLE
2022 10 25 - Green Software Patterns Agenda & Minutes

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/green-software-patterns#131]
## Date
2022-10-25 - 1.30pm UTC 

## Next steps before COP discussed and confirmed
- team to publish each finalized pattern **by 1 Nov**
- editor to do a final review **by 4 Nov** 
- team to process editor's PRs if any **on 7-8 Nov**
- announce code freeze once each edit has been processed 

## PM issues discussed
- [x] https://github.com/Green-Software-Foundation/green-software-patterns/issues/80 - 33/4 as of the 25th
- [x] https://github.com/Green-Software-Foundation/green-software-patterns/issues/81 - after COP
- [x] https://github.com/Green-Software-Foundation/green-software-patterns/issues/87 - no new applications
- [x] https://github.com/Green-Software-Foundation/green-software-patterns/issues/119 - anyone is welcome to pick this up
- [x] https://github.com/Green-Software-Foundation/green-software-patterns/issues/23 - in progress

## Website 
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/105 - Osama to pick this up – ETA?
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/113 - Osama to investigate

## Random
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/127 - discussed
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/126 - discussed
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/123 - discussed
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/122 - discussed
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/91 - discussed
- https://github.com/Green-Software-Foundation/green-software-patterns/issues/121 - Bill is working on this

## Future plans (details and timings to be discussed):
- After COP, we will start a quarterly **consistency review** process. 
- Perform periodic reviews and udpates in line with **changes in SCI**. 
- **Audit our own resources** to make sure we fully comply with our guidelines (graphics, css, svg formats, scripts etc)

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

### Attendees 
**Aditi J., Akshit B., Anita H., Aoife F., Asim H., Bill. J., Franziska H., Markus S., Navveen B., Sarah H., Tammy M.**

**Comment by navveenb** [comment]
attended

**Comment by akshitbatra** [comment]
Attended.

**Comment by holanita** [comment]
attended

**Comment by holanita** [comment]
To be continued in the new weekly agenda: https://github.com/Green-Software-Foundation/green-software-patterns/issues/161
